// Comprehensive Static Mock Data for GitHub Pages Hosting & Standalone Previews
// Matches the Indian Corporate 19-Persona EOMS Dataset

export const STATIC_USERS = [
  { userId: 1, username: 'admin', email: 'admin@eoms.in', roles: ['SYSTEM_ADMIN', 'HR_ADMIN'], employeeId: 1, firstName: 'Rajesh', lastName: 'Nambiar' },
  { userId: 2, username: 'priya.patel', email: 'priya.patel@eoms.in', roles: ['HR_ADMIN'], employeeId: 2, firstName: 'Priya', lastName: 'Patel' },
  { userId: 3, username: 'aarav.sharma', email: 'aarav.sharma@eoms.in', roles: ['EMPLOYEE'], employeeId: 6, firstName: 'Aarav', lastName: 'Sharma' },
  { userId: 4, username: 'vikram.malhotra', email: 'vikram.malhotra@eoms.in', roles: ['DEPARTMENT_MANAGER', 'MANAGER'], employeeId: 3, firstName: 'Vikram', lastName: 'Malhotra' },
  { userId: 5, username: 'rohan.verma', email: 'rohan.verma@eoms.in', roles: ['IT_ADMIN'], employeeId: 4, firstName: 'Rohan', lastName: 'Verma' },
  { userId: 6, username: 'neha.nair', email: 'neha.nair@eoms.in', roles: ['COMPLIANCE_OFFICER', 'HR_SPECIALIST'], employeeId: 5, firstName: 'Neha', lastName: 'Nair' },
  { userId: 7, username: 'sneha.kulkarni', email: 'sneha.kulkarni@eoms.in', roles: ['EMPLOYEE'], employeeId: 7, firstName: 'Sneha', lastName: 'Kulkarni' },
  { userId: 8, username: 'arjun.rao', email: 'arjun.rao@eoms.in', roles: ['EMPLOYEE'], employeeId: 8, firstName: 'Arjun', lastName: 'Rao' },
  { userId: 9, username: 'ananya.iyer', email: 'ananya.iyer@eoms.in', roles: ['HR_SPECIALIST'], employeeId: 9, firstName: 'Ananya', lastName: 'Iyer' },
  { userId: 10, username: 'kabir.mehta', email: 'kabir.mehta@eoms.in', roles: ['RECRUITER'], employeeId: 10, firstName: 'Kabir', lastName: 'Mehta' },
  { userId: 11, username: 'pooja.desai', email: 'pooja.desai@eoms.in', roles: ['PAYROLL_ADMIN'], employeeId: 12, firstName: 'Pooja', lastName: 'Desai' },
  { userId: 12, username: 'aditya.sengupta', email: 'aditya.sengupta@eoms.in', roles: ['EMPLOYEE'], employeeId: 11, firstName: 'Aditya', lastName: 'Sengupta' },
  { userId: 13, username: 'tanvi.reddy', email: 'tanvi.reddy@eoms.in', roles: ['EMPLOYEE'], employeeId: 13, firstName: 'Tanvi', lastName: 'Reddy' },
  { userId: 14, username: 'karthik.krishnan', email: 'karthik.krishnan@eoms.in', roles: ['ONBOARDING_BUDDY'], employeeId: 14, firstName: 'Karthik', lastName: 'Krishnan' },
  { userId: 15, username: 'ritu.choudhury', email: 'ritu.choudhury@eoms.in', roles: ['EMPLOYEE'], employeeId: 15, firstName: 'Ritu', lastName: 'Choudhury' },
];

export const STATIC_DEPARTMENTS = [
  { deptId: 1, deptName: 'Engineering & Technology', code: 'ENG' },
  { deptId: 2, deptName: 'People Operations & HR', code: 'HR' },
  { deptId: 3, deptName: 'IT Infrastructure & Security', code: 'IT' },
  { deptId: 4, deptName: 'Legal & Statutory Compliance', code: 'LEG' },
  { deptId: 5, deptName: 'Finance, Payroll & Taxation', code: 'FIN' },
  { deptId: 6, deptName: 'Product Management & UX Design', code: 'PRD' },
  { deptId: 7, deptName: 'Sales & Customer Success', code: 'SCS' },
];

export const STATIC_POSITIONS = [
  { positionId: 1, title: 'Software Development Engineer II (Backend)', deptId: 1, Department: { deptName: 'Engineering & Technology' } },
  { positionId: 2, title: 'Head of People Operations', deptId: 2, Department: { deptName: 'People Operations & HR' } },
  { positionId: 3, title: 'Engineering Director & Department Manager', deptId: 1, Department: { deptName: 'Engineering & Technology' } },
  { positionId: 4, title: 'IT Infrastructure & Asset Provisioning Lead', deptId: 3, Department: { deptName: 'IT Infrastructure & Security' } },
  { positionId: 5, title: 'Statutory & Regulatory Compliance Officer', deptId: 4, Department: { deptName: 'Legal & Statutory Compliance' } },
  { positionId: 6, title: 'Lead Product Designer (UI/UX)', deptId: 6, Department: { deptName: 'Product Management & UX Design' } },
  { positionId: 7, title: 'Associate Systems Engineer', deptId: 1, Department: { deptName: 'Engineering & Technology' } },
  { positionId: 8, title: 'Senior Talent Acquisition Partner', deptId: 2, Department: { deptName: 'People Operations & HR' } },
  { positionId: 9, title: 'India Payroll & Statutory Benefits Lead', deptId: 5, Department: { deptName: 'Finance, Payroll & Taxation' } },
  { positionId: 10, title: 'Staff Site Reliability Engineer', deptId: 1, Department: { deptName: 'Engineering & Technology' } },
];

export const STATIC_EMPLOYEES = [
  {
    employeeId: 1,
    userId: 1,
    firstName: 'Rajesh',
    lastName: 'Nambiar',
    workEmail: 'rajesh.nambiar@eoms.in',
    workLocation: 'Bengaluru (Bellandur Hub)',
    status: 'active',
    hireDate: '2023-01-10',
    Position: { title: 'Chief System Administrator', Department: { deptName: 'IT Infrastructure & Security' } },
    OnboardingPlan: { progressPercent: 100, status: 'completed' },
  },
  {
    employeeId: 2,
    userId: 2,
    firstName: 'Priya',
    lastName: 'Patel',
    workEmail: 'priya.patel@eoms.in',
    workLocation: 'Bengaluru (Bellandur Hub)',
    status: 'active',
    hireDate: '2023-04-15',
    Position: { title: 'Head of People Operations', Department: { deptName: 'People Operations & HR' } },
    OnboardingPlan: { progressPercent: 100, status: 'completed' },
  },
  {
    employeeId: 3,
    userId: 4,
    firstName: 'Vikram',
    lastName: 'Malhotra',
    workEmail: 'vikram.malhotra@eoms.in',
    workLocation: 'Bengaluru (Bellandur Hub)',
    status: 'active',
    hireDate: '2023-06-01',
    Position: { title: 'Engineering Director', Department: { deptName: 'Engineering & Technology' } },
    OnboardingPlan: { progressPercent: 100, status: 'completed' },
  },
  {
    employeeId: 4,
    userId: 5,
    firstName: 'Rohan',
    lastName: 'Verma',
    workEmail: 'rohan.verma@eoms.in',
    workLocation: 'Pune (Hinjawadi Phase 1)',
    status: 'active',
    hireDate: '2023-08-10',
    Position: { title: 'IT Asset Provisioning Lead', Department: { deptName: 'IT Infrastructure & Security' } },
    OnboardingPlan: { progressPercent: 100, status: 'completed' },
  },
  {
    employeeId: 5,
    userId: 6,
    firstName: 'Neha',
    lastName: 'Nair',
    workEmail: 'neha.nair@eoms.in',
    workLocation: 'Gurugram (Cyber City)',
    status: 'active',
    hireDate: '2023-09-01',
    Position: { title: 'Statutory Compliance Officer', Department: { deptName: 'Legal & Statutory Compliance' } },
    OnboardingPlan: { progressPercent: 100, status: 'completed' },
  },
  {
    employeeId: 6,
    userId: 3,
    firstName: 'Aarav',
    lastName: 'Sharma',
    workEmail: 'aarav.sharma@eoms.in',
    workLocation: 'Hyderabad (HITEC City)',
    status: 'onboarding',
    hireDate: '2026-02-01',
    Position: { title: 'Software Development Engineer II (Backend)', Department: { deptName: 'Engineering & Technology' } },
    OnboardingPlan: { progressPercent: 72, status: 'in_progress' },
    Manager: { firstName: 'Vikram', lastName: 'Malhotra' },
  },
  {
    employeeId: 7,
    userId: 7,
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    workEmail: 'sneha.kulkarni@eoms.in',
    workLocation: 'Pune (Hinjawadi Phase 1)',
    status: 'onboarding',
    hireDate: '2026-02-05',
    Position: { title: 'Lead Product Designer (UI/UX)', Department: { deptName: 'Product Management & UX Design' } },
    OnboardingPlan: { progressPercent: 45, status: 'in_progress' },
    Manager: { firstName: 'Vikram', lastName: 'Malhotra' },
  },
  {
    employeeId: 8,
    userId: 8,
    firstName: 'Arjun',
    lastName: 'Rao',
    workEmail: 'arjun.rao@eoms.in',
    workLocation: 'Hyderabad (HITEC City)',
    status: 'active',
    hireDate: '2026-01-10',
    Position: { title: 'Associate Systems Engineer', Department: { deptName: 'Engineering & Technology' } },
    OnboardingPlan: { progressPercent: 100, status: 'completed' },
    Manager: { firstName: 'Vikram', lastName: 'Malhotra' },
  },
];

export const STATIC_CHECKLIST_TASKS = [
  { taskId: 1, title: 'Upload Government Identity Proof (Aadhaar & PAN)', category: 'compliance', priority: 'critical', estimatedMinutes: 20, isMandatory: true, status: 'completed' },
  { taskId: 2, title: 'Complete EPFO Form 11 & UAN declaration', category: 'administrative', priority: 'high', estimatedMinutes: 25, isMandatory: true, status: 'completed' },
  { taskId: 3, title: 'Submit Relieving Letter from previous employer', category: 'administrative', priority: 'high', estimatedMinutes: 15, isMandatory: true, status: 'completed' },
  { taskId: 4, title: 'Collect laptop from IT & complete hardware handover sign-off', category: 'it_setup', priority: 'critical', estimatedMinutes: 30, isMandatory: true, status: 'completed' },
  { taskId: 5, title: 'Activate Google Workspace & 2FA corporate authenticator', category: 'it_setup', priority: 'critical', estimatedMinutes: 25, isMandatory: true, status: 'completed' },
  { taskId: 6, title: 'Acknowledge POSH Act 2013 Policy & ICC Committee details', category: 'compliance', priority: 'critical', estimatedMinutes: 30, isMandatory: true, status: 'completed' },
  { taskId: 7, title: 'Complete Information Security & DPDP Compliance Module', category: 'training', priority: 'critical', estimatedMinutes: 60, isMandatory: true, status: 'in_progress' },
  { taskId: 8, title: 'Configure local Docker, Node.js & GitHub SSH keys', category: 'it_setup', priority: 'high', estimatedMinutes: 90, isMandatory: true, status: 'in_progress' },
  { taskId: 9, title: 'Complete POSH Sensitization Interactive Course & Quiz', category: 'compliance', priority: 'critical', estimatedMinutes: 45, isMandatory: true, status: 'not_started' },
  { taskId: 10, title: 'Conduct 30-Day Check-in & Feedback Survey with Manager', category: 'manager_meeting', priority: 'high', estimatedMinutes: 45, isMandatory: true, status: 'not_started' },
];

export const STATIC_ASSETS = [
  {
    assetId: 1,
    serialNumber: 'C02XYZ108M3',
    assetTag: 'BLR-MBP-2026-108',
    status: 'allocated',
    purchasedAt: '2025-11-01',
    AssetModel: {
      modelName: 'MacBook Pro 16" M3 Max (36GB / 1TB)',
      manufacturer: 'Apple',
      specs: '16-core GPU, 36GB Unified Memory, Liquid Retina XDR',
      AssetCategory: { categoryName: 'Laptops & Workstations' },
    },
    AssetAllocations: [
      {
        allocationId: 1,
        employeeId: 6,
        acknowledgementStatus: 'acknowledged',
        allocatedAt: '2026-02-01',
        Employee: { firstName: 'Aarav', lastName: 'Sharma' },
      },
    ],
  },
  {
    assetId: 2,
    serialNumber: 'C02XYZ109M3',
    assetTag: 'BLR-MBP-2026-109',
    status: 'allocated',
    purchasedAt: '2025-11-01',
    AssetModel: {
      modelName: 'MacBook Pro 16" M3 Max (36GB / 1TB)',
      manufacturer: 'Apple',
      specs: '16-core GPU, 36GB Unified Memory, Liquid Retina XDR',
      AssetCategory: { categoryName: 'Laptops & Workstations' },
    },
    AssetAllocations: [
      {
        allocationId: 2,
        employeeId: 7,
        acknowledgementStatus: 'pending',
        allocatedAt: '2026-02-05',
        Employee: { firstName: 'Sneha', lastName: 'Kulkarni' },
      },
    ],
  },
  {
    assetId: 3,
    serialNumber: 'PF2K991A4',
    assetTag: 'HYD-TP-2026-214',
    status: 'allocated',
    purchasedAt: '2025-12-05',
    AssetModel: {
      modelName: 'ThinkPad T14s Gen 5 (32GB / 1TB)',
      manufacturer: 'Lenovo',
      specs: 'AMD Ryzen 7 PRO, 32GB LPDDR5x, OLED display',
      AssetCategory: { categoryName: 'Laptops & Workstations' },
    },
    AssetAllocations: [
      {
        allocationId: 3,
        employeeId: 8,
        acknowledgementStatus: 'acknowledged',
        allocatedAt: '2026-01-10',
        Employee: { firstName: 'Arjun', lastName: 'Rao' },
      },
    ],
  },
  {
    assetId: 4,
    serialNumber: 'PF2K992B5',
    assetTag: 'PUN-TP-2026-215',
    status: 'in_stock',
    purchasedAt: '2025-12-05',
    AssetModel: {
      modelName: 'ThinkPad T14s Gen 5 (32GB / 1TB)',
      manufacturer: 'Lenovo',
      specs: 'AMD Ryzen 7 PRO, 32GB LPDDR5x, OLED display',
      AssetCategory: { categoryName: 'Laptops & Workstations' },
    },
    AssetAllocations: [],
  },
  {
    assetId: 5,
    serialNumber: 'CN088DEL4K',
    assetTag: 'BLR-MON-2026-088',
    status: 'allocated',
    purchasedAt: '2026-01-10',
    AssetModel: {
      modelName: 'UltraSharp 27" 4K USB-C Hub (U2723QE)',
      manufacturer: 'Dell',
      specs: '4K UHD, IPS Black, 90W Power Delivery',
      AssetCategory: { categoryName: 'Displays & Peripherals' },
    },
    AssetAllocations: [
      {
        allocationId: 4,
        employeeId: 6,
        acknowledgementStatus: 'acknowledged',
        allocatedAt: '2026-02-01',
        Employee: { firstName: 'Aarav', lastName: 'Sharma' },
      },
    ],
  },
  {
    assetId: 6,
    serialNumber: 'YK5C-99014',
    assetTag: 'BLR-SEC-2026-014',
    status: 'allocated',
    purchasedAt: '2026-01-10',
    AssetModel: {
      modelName: 'YubiKey 5C NFC',
      manufacturer: 'Yubico',
      specs: 'FIDO2 / WebAuthn, USB-C + NFC hardware security',
      AssetCategory: { categoryName: 'Hardware Security Tokens' },
    },
    AssetAllocations: [
      {
        allocationId: 5,
        employeeId: 6,
        acknowledgementStatus: 'acknowledged',
        allocatedAt: '2026-02-01',
        Employee: { firstName: 'Aarav', lastName: 'Sharma' },
      },
    ],
  },
];

export const STATIC_DOCUMENTS = [
  {
    documentId: 1,
    employeeId: 6,
    fileName: 'aarav_sharma_pan_card.pdf',
    uploadedAt: '2026-02-01',
    DocumentType: { typeName: 'Permanent Account Number (PAN Card)', isMandatory: true },
    Employee: { firstName: 'Aarav', lastName: 'Sharma', workEmail: 'aarav.sharma@eoms.in' },
    DocumentVerifications: [{ status: 'approved', notes: 'PAN Card format matches Income Tax Dept standard (ABCDE1234F). Verified by Compliance.', verifiedAt: '2026-02-02' }],
  },
  {
    documentId: 2,
    employeeId: 6,
    fileName: 'aarav_sharma_aadhaar.pdf',
    uploadedAt: '2026-02-01',
    DocumentType: { typeName: 'Aadhaar Card (e-KYC Proof)', isMandatory: true },
    Employee: { firstName: 'Aarav', lastName: 'Sharma', workEmail: 'aarav.sharma@eoms.in' },
    DocumentVerifications: [{ status: 'approved', notes: 'Aadhaar QR verified successfully.', verifiedAt: '2026-02-02' }],
  },
  {
    documentId: 3,
    employeeId: 7,
    fileName: 'sneha_kulkarni_pan.pdf',
    uploadedAt: '2026-02-06',
    DocumentType: { typeName: 'Permanent Account Number (PAN Card)', isMandatory: true },
    Employee: { firstName: 'Sneha', lastName: 'Kulkarni', workEmail: 'sneha.kulkarni@eoms.in' },
    DocumentVerifications: [{ status: 'pending', notes: null, verifiedAt: null }],
  },
];

export const STATIC_TRAINING_COURSES = [
  {
    courseId: 1,
    title: 'POSH Act 2013 Sensitization & Prevention of Workplace Harassment',
    description: 'Mandatory Indian statutory training on recognizing, preventing, and reporting workplace misconduct under ICC guidelines.',
    durationMinutes: 45,
    isMandatory: true,
    passingScore: 80,
    TrainingRecords: [{ status: 'in_progress', score: 85, progressPercent: 64 }],
  },
  {
    courseId: 2,
    title: 'Information Security & DPDP Act Compliance',
    description: 'Data protection standards, handling customer PII, corporate phishing defense, and secure engineering practices.',
    durationMinutes: 60,
    isMandatory: true,
    passingScore: 85,
    TrainingRecords: [{ status: 'completed', score: 92, progressPercent: 100 }],
  },
  {
    courseId: 3,
    title: 'EOMS Cloud Infrastructure & Git Flow Standards',
    description: 'Microservices architecture, Docker environment setup, PR code review conventions, and CI/CD deployment policies.',
    durationMinutes: 90,
    isMandatory: true,
    passingScore: 80,
    TrainingRecords: [{ status: 'completed', score: 95, progressPercent: 100 }],
  },
  {
    courseId: 4,
    title: 'Corporate Code of Conduct & Anti-Bribery Standards',
    description: 'Company ethics, gift policies, conflict of interest, and whistle-blower mechanisms.',
    durationMinutes: 30,
    isMandatory: true,
    passingScore: 80,
    TrainingRecords: [{ status: 'completed', score: 100, progressPercent: 100 }],
  },
];

export const STATIC_POSH_QUESTIONS = [
  {
    id: 1,
    question: 'Under the POSH Act 2013, what constitutes the Internal Complaints Committee (ICC)?',
    options: [
      'A mandatory committee headed by a senior woman employee with at least 50% women members and an external NGO representative.',
      'An optional informal committee formed by HR on an ad-hoc basis.',
      'A board of executive directors with no external members.',
      'A police liaison desk located at the corporate premises.',
    ],
    correctIndex: 0,
  },
  {
    id: 2,
    question: 'Within how many months from the date of an incident must an aggrieved woman submit a formal complaint to the ICC?',
    options: [
      '1 month',
      '3 months (extendable by another 3 months with recorded justification)',
      '12 months',
      'No time limit applies',
    ],
    correctIndex: 1,
  },
  {
    id: 3,
    question: 'Which of the following behaviors is categorized as sexual harassment under the Act?',
    options: [
      'Unwelcome sexually determined physical contact or advances.',
      'Demand or request for sexual favors.',
      'Making sexually colored remarks or showing pornography.',
      'All of the above.',
    ],
    correctIndex: 3,
  },
  {
    id: 4,
    question: 'Are digital workspaces, video calls, Slack channels, and official off-site events covered under POSH jurisdiction?',
    options: [
      'No, POSH only applies to physical corporate office buildings.',
      'Yes, the definition of "workplace" covers any place visited by the employee arising out of or during employment, including electronic communications.',
      'Only if recorded on corporate company servers.',
      'Only if the victim was working from home during business hours.',
    ],
    correctIndex: 1,
  },
  {
    id: 5,
    question: 'What is the required confidentiality standard regarding ICC proceedings and complainant identities?',
    options: [
      'ICC reports should be published on the company intranet for transparency.',
      'Strict confidentiality must be maintained; publishing or disseminating identities or inquiry contents is illegal and subject to statutory penalties.',
      'Information may be freely shared among team leads.',
      'Confidentiality only applies until the inquiry concludes.',
    ],
    correctIndex: 1,
  },
];

export const STATIC_NOTIFICATIONS = [
  {
    notificationId: 1,
    userId: 3,
    title: 'Welcome to EOMS Technologies India! 🎉',
    message: 'Welcome Aarav! Your 90-day onboarding journey has officially begun. Check your Day 1 checklist.',
    channel: 'in_app',
    isRead: true,
    createdAt: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
  },
  {
    notificationId: 2,
    userId: 3,
    title: 'Hardware Handover Acknowledged ✓',
    message: 'Your MacBook Pro 16" (BLR-MBP-2026-108) allocation has been successfully acknowledged.',
    channel: 'in_app',
    isRead: true,
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
  },
  {
    notificationId: 3,
    userId: 3,
    title: 'Reminder: Complete Mandatory POSH Training',
    message: 'Please complete the POSH Act 2013 compliance course and final assessment before the 30-day milestone.',
    channel: 'in_app',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    notificationId: 4,
    userId: 2,
    title: 'New Statutory Document Pending Review ▤',
    message: 'Sneha Kulkarni has uploaded her PAN Card for verification. Awaiting Compliance approval.',
    channel: 'in_app',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];

export const STATIC_REPORTS_SUMMARY = {
  employees: {
    total: 19,
    active: 17,
    onboarding: 2,
  },
  onboarding: {
    totalPlans: 8,
    completedPlans: 5,
    inProgressPlans: 3,
    averageProgressPercent: 78.5,
    completionRatePercent: 88,
  },
  compliance: {
    totalDocuments: 24,
    pendingVerifications: 2,
    approvedVerifications: 22,
    complianceRatePercent: 92,
  },
  assets: {
    totalAssets: 18,
    allocatedAssets: 14,
    inStockAssets: 4,
    utilizationPercent: 78,
  },
  training: {
    totalRecords: 38,
    completedRecords: 34,
    completionPercent: 89,
  },
};

export const STATIC_AUDIT_LOGS = [
  {
    logId: 1,
    action: 'LOGIN',
    targetTable: 'system_users',
    targetId: '2',
    ipAddress: '127.0.0.1',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    Actor: { userId: 2, username: 'priya.patel', email: 'priya.patel@eoms.in' },
  },
  {
    logId: 2,
    action: 'CREATE_EMPLOYEE',
    targetTable: 'employees',
    targetId: '6',
    ipAddress: '127.0.0.1',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    createdAt: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    Actor: { userId: 2, username: 'priya.patel', email: 'priya.patel@eoms.in' },
  },
  {
    logId: 3,
    action: 'ALLOCATE_ASSET',
    targetTable: 'assets',
    targetId: '1',
    ipAddress: '127.0.0.1',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    Actor: { userId: 5, username: 'rohan.verma', email: 'rohan.verma@eoms.in' },
  },
  {
    logId: 4,
    action: 'VERIFY_DOCUMENT',
    targetTable: 'documents',
    targetId: '1',
    ipAddress: '127.0.0.1',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
    createdAt: new Date(Date.now() - 3600000 * 24 * 1).toISOString(),
    Actor: { userId: 6, username: 'neha.nair', email: 'neha.nair@eoms.in' },
  },
];
